### ISSUE TITLE
Dwarves spawn in Mushroom Fields 1.19.2 3.0.1 - Annoyance

### ISSUE THREAD

**Issue by JohnWJarrett** [SaphieNyako/Feywild#113]
### Describe your idea

So, I have a base inside a cave inside a mushroom biome and have a minecolony here and all that good stuff, decided to add this mod late game as I didn't want to mess with vanilla in the immediate vicinity of my base, but now that it's installed all I can hear is "Hurr" "Uhurr" every 4 seconds and it's annoying as all. also, they are spawned en-masse inside my base, I'm pretty sure there is like 15 in here. Can you please limit where they will spawn, or give us an option to do it or even better yet, lock the whole mod inside your own dimension.

**Comment by SaphieNyako** [comment]
What version are you on?
This is an old issue and they shouldn't spawn in the mushroom biome at all.
With changes to world gen this might have become a problem again.
Thanks for report.

**Comment by JohnWJarrett** [comment]
I'm using the latest for 1.19.2, so 1.19.2-3.0.1

**Comment by SaphieNyako** [comment]
The spawn is a bit high compaired to other mobs. So I'll lower that. 
You can change that by making a datapack, since that's how the world gen is regulated now. 

I'll look into a way to prevent them from spawning into the mushroom biome. 

I'll also lower the amount of "Hurr" and "Uhurr", though thats the normal level of annoyance of villagers. 

Next patch.

**Comment by SaphieNyako** [comment]
for the datapack:
data > feywild > forge > biome_modifier > overworld_spawn.json

```
{
  "type": "forge:add_spawns",
  "biomes": "#minecraft:is_overworld",
  "spawners": [
    {
      "type": "feywild:spring_pixie",
      "maxCount": 1,
      "minCount": 1,
      "weight": 1
    },
    {
      "type": "feywild:summer_pixie",
      "maxCount": 1,
      "minCount": 1,
      "weight": 1
    },
    {
      "type": "feywild:autumn_pixie",
      "maxCount": 1,
      "minCount": 1,
      "weight": 1
    },
    {
      "type": "feywild:winter_pixie",
      "maxCount": 1,
      "minCount": 1,
      "weight": 1
    },
    {
      "type": "feywild:dwarf_blacksmith",
      "maxCount": 1,
      "minCount": 1,
      "weight": 3
    }
  ]
}

```
weight should be set to 1 or 0 if you dont want them to spawn at all.

**Comment by JohnWJarrett** [comment]
Will try that out, thanks for the tip.

**Comment by SaphieNyako** [comment]
![2023-03-15_14 39 09](https://user-images.githubusercontent.com/77398437/225359896-27d8d3ba-f2fa-4fed-b37d-5d94ab6bd665.png)
Dwarven invasion...

![2023-03-15_16 26 05](https://user-images.githubusercontent.com/77398437/225359261-3f07a9a1-7588-4862-a3e8-c56440c21210.png)

The dwarven invasion has been stopped!

Made it so they only spawn in biomes with Mineshafts, and dont spawn in the mushroom_fields  biome. Did increase the spawn a bit since now its harder for them to spawn. Still pretty rare. 

I will leave this open till next update is uploaded: 3.0.2

**Comment by JohnWJarrett** [comment]
Awesome! Can't wait to plug it back in, my child will love the Pixies

**Comment by SaphieNyako** [comment]
Also made the Hurr less frequent. But i still think that's the Minecraft level of annoyance. Just not pleasant during an invasion. 😊

**Comment by SaphieNyako** [comment]
3.0.2 is out that fixes this issue.
