### ISSUE TITLE
Null pointer crash Cracked Log

### ISSUE THREAD

**Issue by JohnWJarrett** [SaphieNyako/Feywild#114]
### Minecraft version

1.19.2

### Feywild version

1.19.2-3.0.2

### Forge version

43.2.4

### The latest.log file

https://pastebin.com/L0VquTXk

### Issue description

When clicking on a cracked log the client crashes, the server stays up and other players are fine, but whoever does it CTD's

### Steps to reproduce

Find a Feywild tree
Click
Crash

**Comment by SaphieNyako** [comment]
Thx for reporting! Ill look into it as soon as I can.

**Comment by SaphieNyako** [comment]
- server?  yes 
- single player? yes 
- with quark installed? yes
- without quark installed? yes
- hand? left no, right no
- right clicking with an axe? no - also block has wrong axis. 
- other tools? yes (and quark)

at java.util.Objects.requireNonNull(Objects.java:208) ~[?:?] {}
	at com.feywild.feywild.block.trees.FeyCrackedLogBlock.getToolModifiedState(FeyCrackedLogBlock.java:58) ~[%23188!/:?] {re:classloading}

Method should be @Nullable

Fixes

- Correct Nullable assignment...
- Axis - Stripped Wood Block instead of Log Block

**Comment by SaphieNyako** [comment]
Problem solved after testing. 

Fix in 3.0.3 update
(uploading now)
