### ISSUE TITLE
Block drop issues

### ISSUE THREAD

**Issue by Gronglegrowth** [SaphieNyako/Feywild#116]
### Minecraft version

1.19.2

### Feywild version

1.10.2-3.0.3

### Forge version

43.2.7

### The latest.log file

n/a

### Issue description

Certain blocks do not have proper drops when mined:

- Fey altar drops nothing, when I expected it to drop itself when broken with a pickaxe
- All mod doors drop two of themselves instead of just one when broken

Some other unrelated things I noticed:

- Autumn doors don't appear to have a localized name (game is set to en_us language)
- Blossom and hexen doors' inventory icons appear very stretched compared to the other doors

**Comment by SaphieNyako** [comment]
Thanks for reporting these issues!

Next update: 
- Fey altar will drop itself when broken with pickaxe. 
- The loottable is auto generated by LibX, I reported it to Noeppi. For next update ill make the loot table jsons myself and manual add them before uploading. 
- added the localized name for the autumn tree door
- The door icons will be replaced. Nano made special door icons for the 16x16 redux. Ill be using these since they allign more with how minecraft does them. 

If you find more let me know pls !

**Comment by SaphieNyako** [comment]
Updated to 3.1.0 wich will fix all these issues.
